## **Batch Gredient Descent**

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

import numpy as np

from sklearn.datasets import load_diabetes

In [12]:
x,y = load_diabetes(return_X_y=True)
x.shape

(442, 10)

In [11]:
y.shape

(442,)

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [16]:
reg.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [17]:
reg.intercept_

151.34560453985995

In [18]:
y_pred = reg.predict(x_test)
y_pred

array([139.5475584 , 179.51720835, 134.03875572, 291.41702925,
       123.78965872,  92.1723465 , 258.23238899, 181.33732057,
        90.22411311, 108.63375858,  94.13865744, 168.43486358,
        53.5047888 , 206.63081659, 100.12925869, 130.66657085,
       219.53071499, 250.7803234 , 196.3688346 , 218.57511815,
       207.35050182,  88.48340941,  70.43285917, 188.95914235,
       154.8868162 , 159.36170122, 188.31263363, 180.39094033,
        47.99046561, 108.97453871, 174.77897633,  86.36406656,
       132.95761215, 184.53819483, 173.83220911, 190.35858492,
       124.4156176 , 119.65110656, 147.95168682,  59.05405241,
        71.62331856, 107.68284704, 165.45365458, 155.00975931,
       171.04799096,  61.45761356,  71.66672581, 114.96732206,
        51.57975523, 167.57599528, 152.52291955,  62.95568515,
       103.49741722, 109.20751489, 175.64118426, 154.60296242,
        94.41704366, 210.74209145, 120.2566205 ,  77.61585399,
       187.93203995, 206.49337474, 140.63167076, 105.59

In [19]:
r2_score(y_test,y_pred)

0.4526027629719195

In [20]:
x_train.shape

(353, 10)

In [37]:
class GDRegressor:
    def __init__(self,learning_rzate=0.1,epochs=100):
      self.learning_rate = learning_rzate
      self.epochs = epochs
      self.coef_ = None
      self.intercept_ = None

    def fit(self,x,y):
        # initilize your coefficient
        self.intercept_ = 0
        self.coef_ = np.ones(x.shape[1])

        for i in range(self.epochs):
            # update all the cpef_ and its intercept
            y_hat = np.dot(x_train,self.coef_)+self.intercept_

            intercept_der = -2 * np.mean(y_train - y_hat)
            self.intercept_ = self.intercept_ - self.learning_rate * intercept_der

            coef_der = -2 * np.dot((y_train - y_hat),x_train)/x_train.shape[0]
            self.coef_ = self.coef_ - self.learning_rate * coef_der

        print(self.coef_,self.intercept_)

    def predict(self,x):
        return np.dot(x,self.coef_)+self.intercept_

In [38]:
gdr = GDRegressor(0.5,300)
gdr.fit(x_train,y_train)

[  58.89157736  -75.71885298  337.12309796  235.06289983    9.57023717
  -23.90168147 -172.97186937  147.75965637  269.70093703  147.36947837] 151.9582400098892


In [39]:
y_pred2 = gdr.predict(x_test)
y_pred2

array([160.08817588, 163.27851565, 157.48020435, 266.53862292,
       144.06405384, 122.78073668, 230.64067326, 200.08566961,
       106.93951401, 132.24113354, 109.77718448, 139.96566314,
        72.19971147, 207.68444282, 121.27175593, 135.23215685,
       217.11411452, 235.54687518, 169.96370799, 205.62709283,
       177.44767246, 107.78619443,  90.61670216, 186.44148646,
       143.81981529, 165.56620577, 178.92682627, 172.95456575,
        65.35100472, 138.44638197, 172.9249102 , 105.28789496,
       142.83760929, 182.01790402, 175.96271258, 186.01473118,
       139.95212929, 144.0358298 , 170.48573527,  77.43939508,
        99.86950402, 126.21075531, 153.22549513, 169.52769439,
       168.20508101,  82.32780949,  91.51117117, 105.13130901,
        75.95970489, 143.76580203, 133.86839956,  77.38650525,
       133.78604391, 116.64376381, 182.41321724, 139.66460159,
       115.86809896, 186.60545887, 115.61325772,  76.49768564,
       184.39695038, 174.14833922, 136.54315052, 129.11

In [41]:
r2_score(y_test,y_pred2)

0.4410290723979342

## **Stochstic Gradient Descent**

In [43]:
import sklearn


In [46]:
x,y=sklearn.datasets.load_diabetes(return_X_y=True)
x.shape

(442, 10)

In [47]:
y.shape

(442,)

In [49]:
x_Train,x_test,y_train,y_test = sklearn.model_selection.train_test_split(x,y,test_size=0.2,random_state=42)

In [52]:
lr = sklearn.linear_model.LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [53]:
lr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [54]:
lr.intercept_

151.34560453985995

In [57]:
y_pred=lr.predict(x_test)
y_pred

array([139.5475584 , 179.51720835, 134.03875572, 291.41702925,
       123.78965872,  92.1723465 , 258.23238899, 181.33732057,
        90.22411311, 108.63375858,  94.13865744, 168.43486358,
        53.5047888 , 206.63081659, 100.12925869, 130.66657085,
       219.53071499, 250.7803234 , 196.3688346 , 218.57511815,
       207.35050182,  88.48340941,  70.43285917, 188.95914235,
       154.8868162 , 159.36170122, 188.31263363, 180.39094033,
        47.99046561, 108.97453871, 174.77897633,  86.36406656,
       132.95761215, 184.53819483, 173.83220911, 190.35858492,
       124.4156176 , 119.65110656, 147.95168682,  59.05405241,
        71.62331856, 107.68284704, 165.45365458, 155.00975931,
       171.04799096,  61.45761356,  71.66672581, 114.96732206,
        51.57975523, 167.57599528, 152.52291955,  62.95568515,
       103.49741722, 109.20751489, 175.64118426, 154.60296242,
        94.41704366, 210.74209145, 120.2566205 ,  77.61585399,
       187.93203995, 206.49337474, 140.63167076, 105.59

In [58]:
sklearn.metrics.r2_score(y_test,y_pred)

0.4526027629719195

In [60]:
# our own GD class
class SGDRegressor:
    def __init__(self,learning_rate=0.01,epochs = 100):
        self.coef_ = None
        self.intercept_ = None
        self.learning_rate = learning_rate
        self.epochs = epochs

    def fit(self,x_train,y_train):

        # init.. coef
        self.intercept_ = 0
        self.coef_ = np.ones(x_train.shape[1])

        for i in range(self.epochs):
            for j in range(x_train.shape[0]):
                # update all the coefecient and it,s intercept
                idx = np.random.randint(0,x_train.shape[1])

                y_hat = np.dot(x_train[idx],self.coef_)+self.intercept_

                intercept_Der = -2 * (y_train[idx]-y_hat)
                self.intercept_ = self.intercept_ - self.learning_rate * intercept_Der

            coef_der = -2 * np.dot((y_train[idx]-y_hat),x_train[idx])
            self.coef_ = self.coef_ -self.learning_rate * coef_der

        print(self.coef_,self.intercept_)

    def predict(self,x_test):
        return np.dot(x_test,self.coef_)+self.intercept_

In [83]:
sgdr = SGDRegressor(learning_rate = 0.01,epochs = 40)
sgdr.fit(x_train,y_train)

[ 1.90882659  1.82039637  3.53538557  4.12092677  1.5145      0.92032796
 -0.91337087  2.4549303   4.05424702  4.67069704] 144.79936968875992


In [84]:
y_pred=sgdr.predict(x_test)

In [85]:
sklearn.metrics.r2_score(y_test,y_pred)

0.012907475581095729

In [86]:
# using derived class
from sklearn.linear_model import SGDRegressor

In [88]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.01,max_iter=40)

In [89]:
sgd.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_stochastic_gradient.py:1548: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


SGDRegressor(learning_rate='constant', max_iter=40)

In [90]:
sgd.coef_

array([  51.06060637,  -25.83126748,  215.06635319,  155.4562201 ,
         34.04590426,   14.5821305 , -122.34752753,  119.40812956,
        183.58657758,  116.93753954])

In [91]:
sgd.intercept_

array([151.21692994])

In [92]:
sgd.predict(x_test)

array([164.03843914, 155.84859069, 160.83222816, 234.6762184 ,
       150.80327181, 136.15387844, 206.59892632, 191.68923142,
       120.82680946, 140.65564455, 122.68386981, 137.74157317,
        90.05664034, 193.57523505, 130.54978635, 136.57188671,
       199.96478907, 213.03546515, 156.52816225, 190.64564806,
       164.66098597, 122.93438852, 106.82286896, 177.25111775,
       141.80990487, 161.37057967, 169.3333187 , 166.04013446,
        87.01520341, 146.61030611, 165.8409338 , 117.97620067,
       146.75252327, 174.1749002 , 171.43814823, 177.29726992,
       144.98775612, 150.75863804, 170.20714996,  97.88345793,
       114.96870593, 134.23489324, 150.13790139, 169.14851266,
       162.47529056, 102.02245928, 105.97834954, 113.34284761,
        95.47673391, 142.07085872, 130.96546725,  96.55777846,
       142.23116925, 125.19931152, 179.85700689, 137.35533454,
       128.0475172 , 173.09926552, 123.21174687,  93.67132979,
       178.05650118, 162.3530444 , 136.8626129 , 137.36

In [93]:
sklearn.metrics.r2_score(y_test,sgd.predict(x_test))

0.3830615832023039

## **mini batch gredient descent**

In [94]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [96]:
x,y=load_diabetes(return_X_y=True)

In [97]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [98]:
bgdr = LinearRegression()
bgdr.fit(x_train,y_train)

LinearRegression()

In [99]:
bgdr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [100]:
bgdr.intercept_

151.34560453985995

In [102]:
y_pred = bgdr.predict(x_test)

In [103]:
r2_score(y_test,y_pred)

0.4526027629719195

In [104]:
import random

In [112]:
class MBGDRegressor:
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        self.coef_ = None
        self.intercept_ = None
        self.batch_size = batch_size
        self.learning_rate = learning_rate
        self.epochs = epochs

    def fit(self,x_train,y_train):
        # initilize coefecients
        self.intercept_ = 0
        self.coef_ = np.ones(x_train.shape[1])

        for i in range(self.epochs):
            for j in range(x_train.shape[0]/self.batch_size):

                idx = random.sample(range(x_train.shape[0]),self.batch_size)

                y_hat = np.dot(x_train[idx],self.coef_) + self.intercept_

                intercept_der  = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - self.learning_rate * intercept_der

                coef_der = -2 * np.dot((y_train[idx] - y_hat),x_train[idx])
                self.coef = self.coef_ - self.learning_rate*coef_der
        print(self.coef_,self.intercept_)

    def predict(self,x_test):
        return np.dot(x_test,self.coef_)+self.intercept_

In [113]:
mbg = MBGDRegressor(batch_size=x_train.shape[0]/50,learning_rate=0.01,epochs=100)

In [114]:
mbg.fit(x_train,y_train)

TypeError: 'float' object cannot be interpreted as an integer

In [117]:
from sklearn.linear_model import SGDRegressor

In [118]:
sgd = SGDRegressor(learning_rate = 'constant',eta0=0.1)

In [120]:
import random

In [122]:
batch_size=35

for i in range(100):
    idx=random.sample(range(x_train[0]),batch_size)
    sgd.partial_fit(x_train[idx],y_train[idx])

TypeError: only integer scalar arrays can be converted to a scalar index